[tool.isort]
profile = "black"
skip = ["icefall/__init__.py"]

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.github
)/
  | icefall\/__init__\.py
  | icefall\/diagnostics\.py
  | icefall\/profiler\.py
'''
